// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkgs/dto/raft.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define RPC messages
type RaftRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Args:
	//
	//	*RaftRPC_VoteRequest
	//	*RaftRPC_VoteResponse
	//	*RaftRPC_LogRequest
	//	*RaftRPC_LogResponse
	//	*RaftRPC_NodeStatusRequest
	//	*RaftRPC_NodeStatusResponse
	//	*RaftRPC_SetCommandRequest
	//	*RaftRPC_OkResponse
	Args          isRaftRPC_Args `protobuf_oneof:"args"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRPC) Reset() {
	*x = RaftRPC{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRPC) ProtoMessage() {}

func (x *RaftRPC) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRPC.ProtoReflect.Descriptor instead.
func (*RaftRPC) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RaftRPC) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RaftRPC) GetArgs() isRaftRPC_Args {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RaftRPC) GetVoteRequest() *VoteRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_VoteRequest); ok {
			return x.VoteRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetVoteResponse() *VoteResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_VoteResponse); ok {
			return x.VoteResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetLogRequest() *LogRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_LogRequest); ok {
			return x.LogRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetLogResponse() *LogResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_LogResponse); ok {
			return x.LogResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetNodeStatusRequest() *NodeStatusRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_NodeStatusRequest); ok {
			return x.NodeStatusRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetNodeStatusResponse() *NodeStatusResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_NodeStatusResponse); ok {
			return x.NodeStatusResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetSetCommandRequest() *SetCommandRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_SetCommandRequest); ok {
			return x.SetCommandRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetOkResponse() *OkResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

type isRaftRPC_Args interface {
	isRaftRPC_Args()
}

type RaftRPC_VoteRequest struct {
	VoteRequest *VoteRequest `protobuf:"bytes,2,opt,name=voteRequest,proto3,oneof"`
}

type RaftRPC_VoteResponse struct {
	VoteResponse *VoteResponse `protobuf:"bytes,3,opt,name=voteResponse,proto3,oneof"`
}

type RaftRPC_LogRequest struct {
	LogRequest *LogRequest `protobuf:"bytes,4,opt,name=logRequest,proto3,oneof"`
}

type RaftRPC_LogResponse struct {
	LogResponse *LogResponse `protobuf:"bytes,5,opt,name=logResponse,proto3,oneof"`
}

type RaftRPC_NodeStatusRequest struct {
	NodeStatusRequest *NodeStatusRequest `protobuf:"bytes,6,opt,name=nodeStatusRequest,proto3,oneof"`
}

type RaftRPC_NodeStatusResponse struct {
	NodeStatusResponse *NodeStatusResponse `protobuf:"bytes,7,opt,name=nodeStatusResponse,proto3,oneof"`
}

type RaftRPC_SetCommandRequest struct {
	SetCommandRequest *SetCommandRequest `protobuf:"bytes,8,opt,name=setCommandRequest,proto3,oneof"`
}

type RaftRPC_OkResponse struct {
	OkResponse *OkResponse `protobuf:"bytes,9,opt,name=okResponse,proto3,oneof"`
}

func (*RaftRPC_VoteRequest) isRaftRPC_Args() {}

func (*RaftRPC_VoteResponse) isRaftRPC_Args() {}

func (*RaftRPC_LogRequest) isRaftRPC_Args() {}

func (*RaftRPC_LogResponse) isRaftRPC_Args() {}

func (*RaftRPC_NodeStatusRequest) isRaftRPC_Args() {}

func (*RaftRPC_NodeStatusResponse) isRaftRPC_Args() {}

func (*RaftRPC_SetCommandRequest) isRaftRPC_Args() {}

func (*RaftRPC_OkResponse) isRaftRPC_Args() {}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,3,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,4,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,5,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *VoteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VoteRequest) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *VoteRequest) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,3,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *VoteResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	PrefixLength  int32                  `protobuf:"varint,3,opt,name=prefixLength,proto3" json:"prefixLength,omitempty"`
	PrefixTerm    int32                  `protobuf:"varint,4,opt,name=prefixTerm,proto3" json:"prefixTerm,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,5,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	Suffix        []*LogEntry            `protobuf:"bytes,6,rep,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *LogRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *LogRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogRequest) GetPrefixLength() int32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *LogRequest) GetPrefixTerm() int32 {
	if x != nil {
		return x.PrefixTerm
	}
	return 0
}

func (x *LogRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *LogRequest) GetSuffix() []*LogEntry {
	if x != nil {
		return x.Suffix
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=followerId,proto3" json:"followerId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Ack           int32                  `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *LogResponse) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *LogResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogResponse) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{7}
}

type NodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	CurrentTerm   int32                  `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	VotedFor      string                 `protobuf:"bytes,3,opt,name=votedFor,proto3" json:"votedFor,omitempty"`
	CurrentRole   string                 `protobuf:"bytes,4,opt,name=currentRole,proto3" json:"currentRole,omitempty"`
	CurrentLeader string                 `protobuf:"bytes,5,opt,name=currentLeader,proto3" json:"currentLeader,omitempty"`
	CommitLength  int32                  `protobuf:"varint,6,opt,name=commitLength,proto3" json:"commitLength,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,7,rep,name=logEntries,proto3" json:"logEntries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *NodeStatusResponse) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentRole() string {
	if x != nil {
		return x.CurrentRole
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentLeader() string {
	if x != nil {
		return x.CurrentLeader
	}
	return ""
}

func (x *NodeStatusResponse) GetCommitLength() int32 {
	if x != nil {
		return x.CommitLength
	}
	return 0
}

func (x *NodeStatusResponse) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

type SetCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommandRequest) Reset() {
	*x = SetCommandRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommandRequest) ProtoMessage() {}

func (x *SetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommandRequest.ProtoReflect.Descriptor instead.
func (*SetCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{9}
}

func (x *SetCommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCommandRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{10}
}

func (x *OkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pkgs_dto_raft_proto protoreflect.FileDescriptor

const file_pkgs_dto_raft_proto_rawDesc = "" +
	"\n" +
	"\x13pkgs/dto/raft.proto\x12\x03dto\"\x8b\x04\n" +
	"\aRaftRPC\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\vvoteRequest\x18\x02 \x01(\v2\x10.dto.VoteRequestH\x00R\vvoteRequest\x127\n" +
	"\fvoteResponse\x18\x03 \x01(\v2\x11.dto.VoteResponseH\x00R\fvoteResponse\x121\n" +
	"\n" +
	"logRequest\x18\x04 \x01(\v2\x0f.dto.LogRequestH\x00R\n" +
	"logRequest\x124\n" +
	"\vlogResponse\x18\x05 \x01(\v2\x10.dto.LogResponseH\x00R\vlogResponse\x12F\n" +
	"\x11nodeStatusRequest\x18\x06 \x01(\v2\x16.dto.NodeStatusRequestH\x00R\x11nodeStatusRequest\x12I\n" +
	"\x12nodeStatusResponse\x18\a \x01(\v2\x17.dto.NodeStatusResponseH\x00R\x12nodeStatusResponse\x12F\n" +
	"\x11setCommandRequest\x18\b \x01(\v2\x16.dto.SetCommandRequestH\x00R\x11setCommandRequest\x121\n" +
	"\n" +
	"okResponse\x18\t \x01(\v2\x0f.dto.OkResponseH\x00R\n" +
	"okResponseB\x06\n" +
	"\x04args\"\xa1\x01\n" +
	"\vVoteRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12 \n" +
	"\vcandidateId\x18\x03 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x04 \x01(\x05R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x05 \x01(\x05R\vlastLogTerm\"\\\n" +
	"\fVoteResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12 \n" +
	"\vvoteGranted\x18\x03 \x01(\bR\vvoteGranted\"O\n" +
	"\aCommand\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"F\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12&\n" +
	"\acommand\x18\x02 \x01(\v2\f.dto.CommandR\acommand\"\xcb\x01\n" +
	"\n" +
	"LogRequest\x12\x1a\n" +
	"\bleaderId\x18\x01 \x01(\tR\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\"\n" +
	"\fprefixLength\x18\x03 \x01(\x05R\fprefixLength\x12\x1e\n" +
	"\n" +
	"prefixTerm\x18\x04 \x01(\x05R\n" +
	"prefixTerm\x12\"\n" +
	"\fleaderCommit\x18\x05 \x01(\x05R\fleaderCommit\x12%\n" +
	"\x06suffix\x18\x06 \x03(\v2\r.dto.LogEntryR\x06suffix\"m\n" +
	"\vLogResponse\x12\x1e\n" +
	"\n" +
	"followerId\x18\x01 \x01(\tR\n" +
	"followerId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\x05R\x03ack\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x13\n" +
	"\x11NodeStatusRequest\"\x85\x02\n" +
	"\x12NodeStatusResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x05R\vcurrentTerm\x12\x1a\n" +
	"\bvotedFor\x18\x03 \x01(\tR\bvotedFor\x12 \n" +
	"\vcurrentRole\x18\x04 \x01(\tR\vcurrentRole\x12$\n" +
	"\rcurrentLeader\x18\x05 \x01(\tR\rcurrentLeader\x12\"\n" +
	"\fcommitLength\x18\x06 \x01(\x05R\fcommitLength\x12-\n" +
	"\n" +
	"logEntries\x18\a \x03(\v2\r.dto.LogEntryR\n" +
	"logEntries\";\n" +
	"\x11SetCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1c\n" +
	"\n" +
	"OkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02okB\fZ\n" +
	"./pkgs/dtob\x06proto3"

var (
	file_pkgs_dto_raft_proto_rawDescOnce sync.Once
	file_pkgs_dto_raft_proto_rawDescData []byte
)

func file_pkgs_dto_raft_proto_rawDescGZIP() []byte {
	file_pkgs_dto_raft_proto_rawDescOnce.Do(func() {
		file_pkgs_dto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkgs_dto_raft_proto_rawDesc), len(file_pkgs_dto_raft_proto_rawDesc)))
	})
	return file_pkgs_dto_raft_proto_rawDescData
}

var file_pkgs_dto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkgs_dto_raft_proto_goTypes = []any{
	(*RaftRPC)(nil),            // 0: dto.RaftRPC
	(*VoteRequest)(nil),        // 1: dto.VoteRequest
	(*VoteResponse)(nil),       // 2: dto.VoteResponse
	(*Command)(nil),            // 3: dto.Command
	(*LogEntry)(nil),           // 4: dto.LogEntry
	(*LogRequest)(nil),         // 5: dto.LogRequest
	(*LogResponse)(nil),        // 6: dto.LogResponse
	(*NodeStatusRequest)(nil),  // 7: dto.NodeStatusRequest
	(*NodeStatusResponse)(nil), // 8: dto.NodeStatusResponse
	(*SetCommandRequest)(nil),  // 9: dto.SetCommandRequest
	(*OkResponse)(nil),         // 10: dto.OkResponse
}
var file_pkgs_dto_raft_proto_depIdxs = []int32{
	1,  // 0: dto.RaftRPC.voteRequest:type_name -> dto.VoteRequest
	2,  // 1: dto.RaftRPC.voteResponse:type_name -> dto.VoteResponse
	5,  // 2: dto.RaftRPC.logRequest:type_name -> dto.LogRequest
	6,  // 3: dto.RaftRPC.logResponse:type_name -> dto.LogResponse
	7,  // 4: dto.RaftRPC.nodeStatusRequest:type_name -> dto.NodeStatusRequest
	8,  // 5: dto.RaftRPC.nodeStatusResponse:type_name -> dto.NodeStatusResponse
	9,  // 6: dto.RaftRPC.setCommandRequest:type_name -> dto.SetCommandRequest
	10, // 7: dto.RaftRPC.okResponse:type_name -> dto.OkResponse
	3,  // 8: dto.LogEntry.command:type_name -> dto.Command
	4,  // 9: dto.LogRequest.suffix:type_name -> dto.LogEntry
	4,  // 10: dto.NodeStatusResponse.logEntries:type_name -> dto.LogEntry
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkgs_dto_raft_proto_init() }
func file_pkgs_dto_raft_proto_init() {
	if File_pkgs_dto_raft_proto != nil {
		return
	}
	file_pkgs_dto_raft_proto_msgTypes[0].OneofWrappers = []any{
		(*RaftRPC_VoteRequest)(nil),
		(*RaftRPC_VoteResponse)(nil),
		(*RaftRPC_LogRequest)(nil),
		(*RaftRPC_LogResponse)(nil),
		(*RaftRPC_NodeStatusRequest)(nil),
		(*RaftRPC_NodeStatusResponse)(nil),
		(*RaftRPC_SetCommandRequest)(nil),
		(*RaftRPC_OkResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkgs_dto_raft_proto_rawDesc), len(file_pkgs_dto_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkgs_dto_raft_proto_goTypes,
		DependencyIndexes: file_pkgs_dto_raft_proto_depIdxs,
		MessageInfos:      file_pkgs_dto_raft_proto_msgTypes,
	}.Build()
	File_pkgs_dto_raft_proto = out.File
	file_pkgs_dto_raft_proto_goTypes = nil
	file_pkgs_dto_raft_proto_depIdxs = nil
}
