// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkgs/dto/raft.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// remove this enum and move to constants package
type CommandOperation int32

const (
	CommandOperation_SET       CommandOperation = 0
	CommandOperation_DELETE    CommandOperation = 1
	CommandOperation_INCREMENT CommandOperation = 2
	CommandOperation_DECREMENT CommandOperation = 3
)

// Enum value maps for CommandOperation.
var (
	CommandOperation_name = map[int32]string{
		0: "SET",
		1: "DELETE",
		2: "INCREMENT",
		3: "DECREMENT",
	}
	CommandOperation_value = map[string]int32{
		"SET":       0,
		"DELETE":    1,
		"INCREMENT": 2,
		"DECREMENT": 3,
	}
)

func (x CommandOperation) Enum() *CommandOperation {
	p := new(CommandOperation)
	*p = x
	return p
}

func (x CommandOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_pkgs_dto_raft_proto_enumTypes[0].Descriptor()
}

func (CommandOperation) Type() protoreflect.EnumType {
	return &file_pkgs_dto_raft_proto_enumTypes[0]
}

func (x CommandOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandOperation.Descriptor instead.
func (CommandOperation) EnumDescriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{0}
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,3,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,4,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,5,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VoteRequest) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *VoteRequest) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,3,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *VoteResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	PrefixLength  int32                  `protobuf:"varint,3,opt,name=prefixLength,proto3" json:"prefixLength,omitempty"`
	PrefixTerm    int32                  `protobuf:"varint,4,opt,name=prefixTerm,proto3" json:"prefixTerm,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,5,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	Suffix        []*LogEntry            `protobuf:"bytes,6,rep,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *LogRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *LogRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogRequest) GetPrefixLength() int32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *LogRequest) GetPrefixTerm() int32 {
	if x != nil {
		return x.PrefixTerm
	}
	return 0
}

func (x *LogRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *LogRequest) GetSuffix() []*LogEntry {
	if x != nil {
		return x.Suffix
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=followerId,proto3" json:"followerId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Ack           int32                  `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *LogResponse) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *LogResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogResponse) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{4}
}

type NodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	CurrentTerm   int32                  `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	VotedFor      string                 `protobuf:"bytes,3,opt,name=votedFor,proto3" json:"votedFor,omitempty"`
	CurrentRole   string                 `protobuf:"bytes,4,opt,name=currentRole,proto3" json:"currentRole,omitempty"`
	CurrentLeader string                 `protobuf:"bytes,5,opt,name=currentLeader,proto3" json:"currentLeader,omitempty"`
	CommitLength  int32                  `protobuf:"varint,6,opt,name=commitLength,proto3" json:"commitLength,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,7,rep,name=logEntries,proto3" json:"logEntries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *NodeStatusResponse) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentRole() string {
	if x != nil {
		return x.CurrentRole
	}
	return ""
}

func (x *NodeStatusResponse) GetCurrentLeader() string {
	if x != nil {
		return x.CurrentLeader
	}
	return ""
}

func (x *NodeStatusResponse) GetCommitLength() int32 {
	if x != nil {
		return x.CommitLength
	}
	return 0
}

func (x *NodeStatusResponse) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

// Log Entry
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Command       *Command               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *LogEntry) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation CommandOperation       `protobuf:"varint,1,opt,name=operation,proto3,enum=dto.CommandOperation" json:"operation,omitempty"`
	// Types that are valid to be assigned to Args:
	//
	//	*Command_SetCommand
	//	*Command_IncrCommand
	//	*Command_DecrCommand
	//	*Command_RemoveCommand
	Args          isCommand_Args `protobuf_oneof:"args"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{7}
}

func (x *Command) GetOperation() CommandOperation {
	if x != nil {
		return x.Operation
	}
	return CommandOperation_SET
}

func (x *Command) GetArgs() isCommand_Args {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetSetCommand() *SetCommand {
	if x != nil {
		if x, ok := x.Args.(*Command_SetCommand); ok {
			return x.SetCommand
		}
	}
	return nil
}

func (x *Command) GetIncrCommand() *IncrCommand {
	if x != nil {
		if x, ok := x.Args.(*Command_IncrCommand); ok {
			return x.IncrCommand
		}
	}
	return nil
}

func (x *Command) GetDecrCommand() *DecrCommand {
	if x != nil {
		if x, ok := x.Args.(*Command_DecrCommand); ok {
			return x.DecrCommand
		}
	}
	return nil
}

func (x *Command) GetRemoveCommand() *RemoveCommand {
	if x != nil {
		if x, ok := x.Args.(*Command_RemoveCommand); ok {
			return x.RemoveCommand
		}
	}
	return nil
}

type isCommand_Args interface {
	isCommand_Args()
}

type Command_SetCommand struct {
	SetCommand *SetCommand `protobuf:"bytes,2,opt,name=setCommand,proto3,oneof"`
}

type Command_IncrCommand struct {
	IncrCommand *IncrCommand `protobuf:"bytes,3,opt,name=incrCommand,proto3,oneof"`
}

type Command_DecrCommand struct {
	DecrCommand *DecrCommand `protobuf:"bytes,4,opt,name=decrCommand,proto3,oneof"`
}

type Command_RemoveCommand struct {
	RemoveCommand *RemoveCommand `protobuf:"bytes,5,opt,name=removeCommand,proto3,oneof"`
}

func (*Command_SetCommand) isCommand_Args() {}

func (*Command_IncrCommand) isCommand_Args() {}

func (*Command_DecrCommand) isCommand_Args() {}

func (*Command_RemoveCommand) isCommand_Args() {}

type SetCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommand) Reset() {
	*x = SetCommand{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommand) ProtoMessage() {}

func (x *SetCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommand.ProtoReflect.Descriptor instead.
func (*SetCommand) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{8}
}

func (x *SetCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCommand) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IncrCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrCommand) Reset() {
	*x = IncrCommand{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrCommand) ProtoMessage() {}

func (x *IncrCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrCommand.ProtoReflect.Descriptor instead.
func (*IncrCommand) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{9}
}

func (x *IncrCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DecrCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrCommand) Reset() {
	*x = DecrCommand{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrCommand) ProtoMessage() {}

func (x *DecrCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrCommand.ProtoReflect.Descriptor instead.
func (*DecrCommand) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{10}
}

func (x *DecrCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RemoveCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommand) Reset() {
	*x = RemoveCommand{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommand) ProtoMessage() {}

func (x *RemoveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommand.ProtoReflect.Descriptor instead.
func (*RemoveCommand) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Application
type SetCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommandRequest) Reset() {
	*x = SetCommandRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommandRequest) ProtoMessage() {}

func (x *SetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommandRequest.ProtoReflect.Descriptor instead.
func (*SetCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{12}
}

func (x *SetCommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCommandRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkResponse) Reset() {
	*x = OkResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkResponse) ProtoMessage() {}

func (x *OkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkResponse.ProtoReflect.Descriptor instead.
func (*OkResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{13}
}

func (x *OkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Raft RPC
// All the messages that are received from outside in TCP
type RaftRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Args:
	//
	//	*RaftRPC_VoteRequest
	//	*RaftRPC_VoteResponse
	//	*RaftRPC_LogRequest
	//	*RaftRPC_LogResponse
	//	*RaftRPC_NodeStatusRequest
	//	*RaftRPC_NodeStatusResponse
	//	*RaftRPC_OkResponse
	//	*RaftRPC_SetCommandRequest
	//	*RaftRPC_GetCommandRequest
	//	*RaftRPC_GetCommandResponse
	//	*RaftRPC_IncrCommandRequest
	//	*RaftRPC_IncrCommandResponse
	//	*RaftRPC_DecrCommandRequest
	//	*RaftRPC_DecrCommandResponse
	//	*RaftRPC_RemoveCommandRequest
	Args          isRaftRPC_Args `protobuf_oneof:"args"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRPC) Reset() {
	*x = RaftRPC{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRPC) ProtoMessage() {}

func (x *RaftRPC) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRPC.ProtoReflect.Descriptor instead.
func (*RaftRPC) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{14}
}

func (x *RaftRPC) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RaftRPC) GetArgs() isRaftRPC_Args {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RaftRPC) GetVoteRequest() *VoteRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_VoteRequest); ok {
			return x.VoteRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetVoteResponse() *VoteResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_VoteResponse); ok {
			return x.VoteResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetLogRequest() *LogRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_LogRequest); ok {
			return x.LogRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetLogResponse() *LogResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_LogResponse); ok {
			return x.LogResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetNodeStatusRequest() *NodeStatusRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_NodeStatusRequest); ok {
			return x.NodeStatusRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetNodeStatusResponse() *NodeStatusResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_NodeStatusResponse); ok {
			return x.NodeStatusResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetOkResponse() *OkResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetSetCommandRequest() *SetCommandRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_SetCommandRequest); ok {
			return x.SetCommandRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetGetCommandRequest() *GetCommandRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_GetCommandRequest); ok {
			return x.GetCommandRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetGetCommandResponse() *GetCommandResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_GetCommandResponse); ok {
			return x.GetCommandResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetIncrCommandRequest() *IncrCommandRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_IncrCommandRequest); ok {
			return x.IncrCommandRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetIncrCommandResponse() *IncrCommandResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_IncrCommandResponse); ok {
			return x.IncrCommandResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetDecrCommandRequest() *DecrCommandRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_DecrCommandRequest); ok {
			return x.DecrCommandRequest
		}
	}
	return nil
}

func (x *RaftRPC) GetDecrCommandResponse() *DecrCommandResponse {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_DecrCommandResponse); ok {
			return x.DecrCommandResponse
		}
	}
	return nil
}

func (x *RaftRPC) GetRemoveCommandRequest() *RemoveCommandRequest {
	if x != nil {
		if x, ok := x.Args.(*RaftRPC_RemoveCommandRequest); ok {
			return x.RemoveCommandRequest
		}
	}
	return nil
}

type isRaftRPC_Args interface {
	isRaftRPC_Args()
}

type RaftRPC_VoteRequest struct {
	VoteRequest *VoteRequest `protobuf:"bytes,2,opt,name=voteRequest,proto3,oneof"`
}

type RaftRPC_VoteResponse struct {
	VoteResponse *VoteResponse `protobuf:"bytes,3,opt,name=voteResponse,proto3,oneof"`
}

type RaftRPC_LogRequest struct {
	LogRequest *LogRequest `protobuf:"bytes,4,opt,name=logRequest,proto3,oneof"`
}

type RaftRPC_LogResponse struct {
	LogResponse *LogResponse `protobuf:"bytes,5,opt,name=logResponse,proto3,oneof"`
}

type RaftRPC_NodeStatusRequest struct {
	NodeStatusRequest *NodeStatusRequest `protobuf:"bytes,6,opt,name=nodeStatusRequest,proto3,oneof"`
}

type RaftRPC_NodeStatusResponse struct {
	NodeStatusResponse *NodeStatusResponse `protobuf:"bytes,7,opt,name=nodeStatusResponse,proto3,oneof"`
}

type RaftRPC_OkResponse struct {
	OkResponse *OkResponse `protobuf:"bytes,8,opt,name=okResponse,proto3,oneof"`
}

type RaftRPC_SetCommandRequest struct {
	SetCommandRequest *SetCommandRequest `protobuf:"bytes,9,opt,name=setCommandRequest,proto3,oneof"`
}

type RaftRPC_GetCommandRequest struct {
	GetCommandRequest *GetCommandRequest `protobuf:"bytes,10,opt,name=getCommandRequest,proto3,oneof"`
}

type RaftRPC_GetCommandResponse struct {
	GetCommandResponse *GetCommandResponse `protobuf:"bytes,11,opt,name=getCommandResponse,proto3,oneof"`
}

type RaftRPC_IncrCommandRequest struct {
	IncrCommandRequest *IncrCommandRequest `protobuf:"bytes,12,opt,name=incrCommandRequest,proto3,oneof"`
}

type RaftRPC_IncrCommandResponse struct {
	IncrCommandResponse *IncrCommandResponse `protobuf:"bytes,13,opt,name=incrCommandResponse,proto3,oneof"`
}

type RaftRPC_DecrCommandRequest struct {
	DecrCommandRequest *DecrCommandRequest `protobuf:"bytes,14,opt,name=decrCommandRequest,proto3,oneof"`
}

type RaftRPC_DecrCommandResponse struct {
	DecrCommandResponse *DecrCommandResponse `protobuf:"bytes,15,opt,name=decrCommandResponse,proto3,oneof"`
}

type RaftRPC_RemoveCommandRequest struct {
	RemoveCommandRequest *RemoveCommandRequest `protobuf:"bytes,16,opt,name=removeCommandRequest,proto3,oneof"`
}

func (*RaftRPC_VoteRequest) isRaftRPC_Args() {}

func (*RaftRPC_VoteResponse) isRaftRPC_Args() {}

func (*RaftRPC_LogRequest) isRaftRPC_Args() {}

func (*RaftRPC_LogResponse) isRaftRPC_Args() {}

func (*RaftRPC_NodeStatusRequest) isRaftRPC_Args() {}

func (*RaftRPC_NodeStatusResponse) isRaftRPC_Args() {}

func (*RaftRPC_OkResponse) isRaftRPC_Args() {}

func (*RaftRPC_SetCommandRequest) isRaftRPC_Args() {}

func (*RaftRPC_GetCommandRequest) isRaftRPC_Args() {}

func (*RaftRPC_GetCommandResponse) isRaftRPC_Args() {}

func (*RaftRPC_IncrCommandRequest) isRaftRPC_Args() {}

func (*RaftRPC_IncrCommandResponse) isRaftRPC_Args() {}

func (*RaftRPC_DecrCommandRequest) isRaftRPC_Args() {}

func (*RaftRPC_DecrCommandResponse) isRaftRPC_Args() {}

func (*RaftRPC_RemoveCommandRequest) isRaftRPC_Args() {}

type StateMachineState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTerm   int32                  `protobuf:"varint,1,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	VotedFor      string                 `protobuf:"bytes,2,opt,name=voted_for,json=votedFor,proto3" json:"voted_for,omitempty"`
	LogEntry      []*LogEntry            `protobuf:"bytes,3,rep,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	CommitLength  int32                  `protobuf:"varint,4,opt,name=commit_length,json=commitLength,proto3" json:"commit_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateMachineState) Reset() {
	*x = StateMachineState{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateMachineState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateMachineState) ProtoMessage() {}

func (x *StateMachineState) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateMachineState.ProtoReflect.Descriptor instead.
func (*StateMachineState) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{15}
}

func (x *StateMachineState) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *StateMachineState) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

func (x *StateMachineState) GetLogEntry() []*LogEntry {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

func (x *StateMachineState) GetCommitLength() int32 {
	if x != nil {
		return x.CommitLength
	}
	return 0
}

type GetCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequest) Reset() {
	*x = GetCommandRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequest) ProtoMessage() {}

func (x *GetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequest.ProtoReflect.Descriptor instead.
func (*GetCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{16}
}

func (x *GetCommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandResponse) Reset() {
	*x = GetCommandResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandResponse) ProtoMessage() {}

func (x *GetCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandResponse.ProtoReflect.Descriptor instead.
func (*GetCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{17}
}

func (x *GetCommandResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IncrCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrCommandRequest) Reset() {
	*x = IncrCommandRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrCommandRequest) ProtoMessage() {}

func (x *IncrCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrCommandRequest.ProtoReflect.Descriptor instead.
func (*IncrCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{18}
}

func (x *IncrCommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IncrCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrCommandResponse) Reset() {
	*x = IncrCommandResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrCommandResponse) ProtoMessage() {}

func (x *IncrCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrCommandResponse.ProtoReflect.Descriptor instead.
func (*IncrCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{19}
}

func (x *IncrCommandResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IncrCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DecrCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrCommandRequest) Reset() {
	*x = DecrCommandRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrCommandRequest) ProtoMessage() {}

func (x *DecrCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrCommandRequest.ProtoReflect.Descriptor instead.
func (*DecrCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{20}
}

func (x *DecrCommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DecrCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrCommandResponse) Reset() {
	*x = DecrCommandResponse{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrCommandResponse) ProtoMessage() {}

func (x *DecrCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrCommandResponse.ProtoReflect.Descriptor instead.
func (*DecrCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{21}
}

func (x *DecrCommandResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DecrCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommandRequest) Reset() {
	*x = RemoveCommandRequest{}
	mi := &file_pkgs_dto_raft_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommandRequest) ProtoMessage() {}

func (x *RemoveCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkgs_dto_raft_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommandRequest.ProtoReflect.Descriptor instead.
func (*RemoveCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkgs_dto_raft_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveCommandRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RemoveCommandRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkgs_dto_raft_proto protoreflect.FileDescriptor

const file_pkgs_dto_raft_proto_rawDesc = "" +
	"\n" +
	"\x13pkgs/dto/raft.proto\x12\x03dto\"\xa1\x01\n" +
	"\vVoteRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12 \n" +
	"\vcandidateId\x18\x03 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x04 \x01(\x05R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x05 \x01(\x05R\vlastLogTerm\"\\\n" +
	"\fVoteResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12 \n" +
	"\vvoteGranted\x18\x03 \x01(\bR\vvoteGranted\"\xcb\x01\n" +
	"\n" +
	"LogRequest\x12\x1a\n" +
	"\bleaderId\x18\x01 \x01(\tR\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\"\n" +
	"\fprefixLength\x18\x03 \x01(\x05R\fprefixLength\x12\x1e\n" +
	"\n" +
	"prefixTerm\x18\x04 \x01(\x05R\n" +
	"prefixTerm\x12\"\n" +
	"\fleaderCommit\x18\x05 \x01(\x05R\fleaderCommit\x12%\n" +
	"\x06suffix\x18\x06 \x03(\v2\r.dto.LogEntryR\x06suffix\"m\n" +
	"\vLogResponse\x12\x1e\n" +
	"\n" +
	"followerId\x18\x01 \x01(\tR\n" +
	"followerId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\x05R\x03ack\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x13\n" +
	"\x11NodeStatusRequest\"\x85\x02\n" +
	"\x12NodeStatusResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x05R\vcurrentTerm\x12\x1a\n" +
	"\bvotedFor\x18\x03 \x01(\tR\bvotedFor\x12 \n" +
	"\vcurrentRole\x18\x04 \x01(\tR\vcurrentRole\x12$\n" +
	"\rcurrentLeader\x18\x05 \x01(\tR\rcurrentLeader\x12\"\n" +
	"\fcommitLength\x18\x06 \x01(\x05R\fcommitLength\x12-\n" +
	"\n" +
	"logEntries\x18\a \x03(\v2\r.dto.LogEntryR\n" +
	"logEntries\"Z\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12&\n" +
	"\acommand\x18\x03 \x01(\v2\f.dto.CommandR\acommand\"\xa1\x02\n" +
	"\aCommand\x123\n" +
	"\toperation\x18\x01 \x01(\x0e2\x15.dto.CommandOperationR\toperation\x121\n" +
	"\n" +
	"setCommand\x18\x02 \x01(\v2\x0f.dto.SetCommandH\x00R\n" +
	"setCommand\x124\n" +
	"\vincrCommand\x18\x03 \x01(\v2\x10.dto.IncrCommandH\x00R\vincrCommand\x124\n" +
	"\vdecrCommand\x18\x04 \x01(\v2\x10.dto.DecrCommandH\x00R\vdecrCommand\x12:\n" +
	"\rremoveCommand\x18\x05 \x01(\v2\x12.dto.RemoveCommandH\x00R\rremoveCommandB\x06\n" +
	"\x04args\"4\n" +
	"\n" +
	"SetCommand\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1f\n" +
	"\vIncrCommand\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1f\n" +
	"\vDecrCommand\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"!\n" +
	"\rRemoveCommand\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\x11SetCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1c\n" +
	"\n" +
	"OkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xa1\b\n" +
	"\aRaftRPC\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\vvoteRequest\x18\x02 \x01(\v2\x10.dto.VoteRequestH\x00R\vvoteRequest\x127\n" +
	"\fvoteResponse\x18\x03 \x01(\v2\x11.dto.VoteResponseH\x00R\fvoteResponse\x121\n" +
	"\n" +
	"logRequest\x18\x04 \x01(\v2\x0f.dto.LogRequestH\x00R\n" +
	"logRequest\x124\n" +
	"\vlogResponse\x18\x05 \x01(\v2\x10.dto.LogResponseH\x00R\vlogResponse\x12F\n" +
	"\x11nodeStatusRequest\x18\x06 \x01(\v2\x16.dto.NodeStatusRequestH\x00R\x11nodeStatusRequest\x12I\n" +
	"\x12nodeStatusResponse\x18\a \x01(\v2\x17.dto.NodeStatusResponseH\x00R\x12nodeStatusResponse\x121\n" +
	"\n" +
	"okResponse\x18\b \x01(\v2\x0f.dto.OkResponseH\x00R\n" +
	"okResponse\x12F\n" +
	"\x11setCommandRequest\x18\t \x01(\v2\x16.dto.SetCommandRequestH\x00R\x11setCommandRequest\x12F\n" +
	"\x11getCommandRequest\x18\n" +
	" \x01(\v2\x16.dto.GetCommandRequestH\x00R\x11getCommandRequest\x12I\n" +
	"\x12getCommandResponse\x18\v \x01(\v2\x17.dto.GetCommandResponseH\x00R\x12getCommandResponse\x12I\n" +
	"\x12incrCommandRequest\x18\f \x01(\v2\x17.dto.IncrCommandRequestH\x00R\x12incrCommandRequest\x12L\n" +
	"\x13incrCommandResponse\x18\r \x01(\v2\x18.dto.IncrCommandResponseH\x00R\x13incrCommandResponse\x12I\n" +
	"\x12decrCommandRequest\x18\x0e \x01(\v2\x17.dto.DecrCommandRequestH\x00R\x12decrCommandRequest\x12L\n" +
	"\x13decrCommandResponse\x18\x0f \x01(\v2\x18.dto.DecrCommandResponseH\x00R\x13decrCommandResponse\x12O\n" +
	"\x14removeCommandRequest\x18\x10 \x01(\v2\x19.dto.RemoveCommandRequestH\x00R\x14removeCommandRequestB\x06\n" +
	"\x04args\"\xa4\x01\n" +
	"\x11StateMachineState\x12!\n" +
	"\fcurrent_term\x18\x01 \x01(\x05R\vcurrentTerm\x12\x1b\n" +
	"\tvoted_for\x18\x02 \x01(\tR\bvotedFor\x12*\n" +
	"\tlog_entry\x18\x03 \x03(\v2\r.dto.LogEntryR\blogEntry\x12#\n" +
	"\rcommit_length\x18\x04 \x01(\x05R\fcommitLength\"%\n" +
	"\x11GetCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x12GetCommandResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\x12IncrCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"A\n" +
	"\x13IncrCommandResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x12DecrCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"A\n" +
	"\x13DecrCommandResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x14RemoveCommandRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*E\n" +
	"\x10CommandOperation\x12\a\n" +
	"\x03SET\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\r\n" +
	"\tINCREMENT\x10\x02\x12\r\n" +
	"\tDECREMENT\x10\x03B\fZ\n" +
	"./pkgs/dtob\x06proto3"

var (
	file_pkgs_dto_raft_proto_rawDescOnce sync.Once
	file_pkgs_dto_raft_proto_rawDescData []byte
)

func file_pkgs_dto_raft_proto_rawDescGZIP() []byte {
	file_pkgs_dto_raft_proto_rawDescOnce.Do(func() {
		file_pkgs_dto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkgs_dto_raft_proto_rawDesc), len(file_pkgs_dto_raft_proto_rawDesc)))
	})
	return file_pkgs_dto_raft_proto_rawDescData
}

var file_pkgs_dto_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkgs_dto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkgs_dto_raft_proto_goTypes = []any{
	(CommandOperation)(0),        // 0: dto.CommandOperation
	(*VoteRequest)(nil),          // 1: dto.VoteRequest
	(*VoteResponse)(nil),         // 2: dto.VoteResponse
	(*LogRequest)(nil),           // 3: dto.LogRequest
	(*LogResponse)(nil),          // 4: dto.LogResponse
	(*NodeStatusRequest)(nil),    // 5: dto.NodeStatusRequest
	(*NodeStatusResponse)(nil),   // 6: dto.NodeStatusResponse
	(*LogEntry)(nil),             // 7: dto.LogEntry
	(*Command)(nil),              // 8: dto.Command
	(*SetCommand)(nil),           // 9: dto.SetCommand
	(*IncrCommand)(nil),          // 10: dto.IncrCommand
	(*DecrCommand)(nil),          // 11: dto.DecrCommand
	(*RemoveCommand)(nil),        // 12: dto.RemoveCommand
	(*SetCommandRequest)(nil),    // 13: dto.SetCommandRequest
	(*OkResponse)(nil),           // 14: dto.OkResponse
	(*RaftRPC)(nil),              // 15: dto.RaftRPC
	(*StateMachineState)(nil),    // 16: dto.StateMachineState
	(*GetCommandRequest)(nil),    // 17: dto.GetCommandRequest
	(*GetCommandResponse)(nil),   // 18: dto.GetCommandResponse
	(*IncrCommandRequest)(nil),   // 19: dto.IncrCommandRequest
	(*IncrCommandResponse)(nil),  // 20: dto.IncrCommandResponse
	(*DecrCommandRequest)(nil),   // 21: dto.DecrCommandRequest
	(*DecrCommandResponse)(nil),  // 22: dto.DecrCommandResponse
	(*RemoveCommandRequest)(nil), // 23: dto.RemoveCommandRequest
}
var file_pkgs_dto_raft_proto_depIdxs = []int32{
	7,  // 0: dto.LogRequest.suffix:type_name -> dto.LogEntry
	7,  // 1: dto.NodeStatusResponse.logEntries:type_name -> dto.LogEntry
	8,  // 2: dto.LogEntry.command:type_name -> dto.Command
	0,  // 3: dto.Command.operation:type_name -> dto.CommandOperation
	9,  // 4: dto.Command.setCommand:type_name -> dto.SetCommand
	10, // 5: dto.Command.incrCommand:type_name -> dto.IncrCommand
	11, // 6: dto.Command.decrCommand:type_name -> dto.DecrCommand
	12, // 7: dto.Command.removeCommand:type_name -> dto.RemoveCommand
	1,  // 8: dto.RaftRPC.voteRequest:type_name -> dto.VoteRequest
	2,  // 9: dto.RaftRPC.voteResponse:type_name -> dto.VoteResponse
	3,  // 10: dto.RaftRPC.logRequest:type_name -> dto.LogRequest
	4,  // 11: dto.RaftRPC.logResponse:type_name -> dto.LogResponse
	5,  // 12: dto.RaftRPC.nodeStatusRequest:type_name -> dto.NodeStatusRequest
	6,  // 13: dto.RaftRPC.nodeStatusResponse:type_name -> dto.NodeStatusResponse
	14, // 14: dto.RaftRPC.okResponse:type_name -> dto.OkResponse
	13, // 15: dto.RaftRPC.setCommandRequest:type_name -> dto.SetCommandRequest
	17, // 16: dto.RaftRPC.getCommandRequest:type_name -> dto.GetCommandRequest
	18, // 17: dto.RaftRPC.getCommandResponse:type_name -> dto.GetCommandResponse
	19, // 18: dto.RaftRPC.incrCommandRequest:type_name -> dto.IncrCommandRequest
	20, // 19: dto.RaftRPC.incrCommandResponse:type_name -> dto.IncrCommandResponse
	21, // 20: dto.RaftRPC.decrCommandRequest:type_name -> dto.DecrCommandRequest
	22, // 21: dto.RaftRPC.decrCommandResponse:type_name -> dto.DecrCommandResponse
	23, // 22: dto.RaftRPC.removeCommandRequest:type_name -> dto.RemoveCommandRequest
	7,  // 23: dto.StateMachineState.log_entry:type_name -> dto.LogEntry
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pkgs_dto_raft_proto_init() }
func file_pkgs_dto_raft_proto_init() {
	if File_pkgs_dto_raft_proto != nil {
		return
	}
	file_pkgs_dto_raft_proto_msgTypes[7].OneofWrappers = []any{
		(*Command_SetCommand)(nil),
		(*Command_IncrCommand)(nil),
		(*Command_DecrCommand)(nil),
		(*Command_RemoveCommand)(nil),
	}
	file_pkgs_dto_raft_proto_msgTypes[14].OneofWrappers = []any{
		(*RaftRPC_VoteRequest)(nil),
		(*RaftRPC_VoteResponse)(nil),
		(*RaftRPC_LogRequest)(nil),
		(*RaftRPC_LogResponse)(nil),
		(*RaftRPC_NodeStatusRequest)(nil),
		(*RaftRPC_NodeStatusResponse)(nil),
		(*RaftRPC_OkResponse)(nil),
		(*RaftRPC_SetCommandRequest)(nil),
		(*RaftRPC_GetCommandRequest)(nil),
		(*RaftRPC_GetCommandResponse)(nil),
		(*RaftRPC_IncrCommandRequest)(nil),
		(*RaftRPC_IncrCommandResponse)(nil),
		(*RaftRPC_DecrCommandRequest)(nil),
		(*RaftRPC_DecrCommandResponse)(nil),
		(*RaftRPC_RemoveCommandRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkgs_dto_raft_proto_rawDesc), len(file_pkgs_dto_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkgs_dto_raft_proto_goTypes,
		DependencyIndexes: file_pkgs_dto_raft_proto_depIdxs,
		EnumInfos:         file_pkgs_dto_raft_proto_enumTypes,
		MessageInfos:      file_pkgs_dto_raft_proto_msgTypes,
	}.Build()
	File_pkgs_dto_raft_proto = out.File
	file_pkgs_dto_raft_proto_goTypes = nil
	file_pkgs_dto_raft_proto_depIdxs = nil
}
